// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routes.sql

package dbgen

import (
	"context"
)

const addRouteHistory = `-- name: AddRouteHistory :exec
INSERT INTO route_history (user_id, route_hash, spot_ids) VALUES (?, ?, ?)
`

type AddRouteHistoryParams struct {
	UserID    string `json:"user_id"`
	RouteHash string `json:"route_hash"`
	SpotIds   string `json:"spot_ids"`
}

func (q *Queries) AddRouteHistory(ctx context.Context, arg AddRouteHistoryParams) error {
	_, err := q.db.ExecContext(ctx, addRouteHistory, arg.UserID, arg.RouteHash, arg.SpotIds)
	return err
}

const getRecentRouteHashes = `-- name: GetRecentRouteHashes :many
SELECT route_hash FROM route_history 
WHERE user_id = ? 
ORDER BY created_at DESC 
LIMIT 20
`

func (q *Queries) GetRecentRouteHashes(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getRecentRouteHashes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var route_hash string
		if err := rows.Scan(&route_hash); err != nil {
			return nil, err
		}
		items = append(items, route_hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpotsWithHours = `-- name: GetSpotsWithHours :many
SELECT id, name, description, category, latitude, longitude, address, opening_time, closing_time, closed_days
FROM spots
`

type GetSpotsWithHoursRow struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Category    string  `json:"category"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
	Address     *string `json:"address"`
	OpeningTime *string `json:"opening_time"`
	ClosingTime *string `json:"closing_time"`
	ClosedDays  *string `json:"closed_days"`
}

func (q *Queries) GetSpotsWithHours(ctx context.Context) ([]GetSpotsWithHoursRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpotsWithHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSpotsWithHoursRow{}
	for rows.Next() {
		var i GetSpotsWithHoursRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Latitude,
			&i.Longitude,
			&i.Address,
			&i.OpeningTime,
			&i.ClosingTime,
			&i.ClosedDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
